const INITIAL_LEADS = [
  // Himachal Pradesh Leads
  {
    id: "hp-1",
    name: "Old Bridge Cafe",
    type: "Café",
    location: "Old Manali",
    region: "Himachal Pradesh",
    rating: 4.9,
    reviewsCount: 634,
    phone: "078762 77937",
    status: "To contact",
    notes: "Riverside café in Old Manali. Great reviews. Pitch own site + direct WhatsApp orders + Google visibility.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "hp-2",
    name: "High Beat Cafe",
    type: "Café",
    location: "Old Manali",
    region: "Himachal Pradesh",
    rating: 4.9,
    reviewsCount: 96,
    phone: "096025 62794",
    status: "To contact",
    notes: "Café + stay. Good targets as they lose direct bookings to OTAs. Pitch own site to save commissions.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "hp-3",
    name: "Shivu Paragliding",
    type: "Adventure/Tour",
    location: "Manali (Burua)",
    region: "Himachal Pradesh",
    rating: 4.9,
    reviewsCount: 172,
    phone: "098178 80996",
    status: "To contact",
    notes: "Adventure sports provider. Needs booking calendar or WhatsApp booking flow to capture direct tourist queries.",
    source: "Google Maps",
    revenuePotential: 10000
  },

  // Uttarakhand Leads
  {
    id: "ut-1",
    name: "The Blue Art Cafe",
    type: "Café",
    location: "Tapovan, Rishikesh",
    region: "Uttarakhand",
    rating: 4.8,
    reviewsCount: 212,
    phone: "087912 98999",
    status: "To contact",
    notes: "Tapovan café. Warm prospect: owner actively replies to Google reviews and posts updates.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "ut-2",
    name: "Omya Cafe",
    type: "Café",
    location: "Tapovan, Rishikesh",
    region: "Uttarakhand",
    rating: 4.8,
    reviewsCount: 205,
    phone: "099273 40910",
    status: "To contact",
    notes: "Cozy Tapovan café. High-rating active profile but no domain.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "ut-3",
    name: "Brew Casa",
    type: "Café",
    location: "Rajpur Rd, Dehradun",
    region: "Uttarakhand",
    rating: 4.8,
    reviewsCount: 129,
    phone: "073029 08283",
    status: "To contact",
    notes: "Boutique café + gift shop. Warm prospect: owner actively replies to reviews and posts updates.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Mumbai - Electricians Andheri West
  {
    id: "mum-elec-1",
    name: "Global Electricals",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 35,
    phone: "084509 84351",
    status: "To contact",
    notes: "Local electrician service. Pitch high Google local search visibility.",
    source: "Google Maps",
    revenuePotential: 6000
  },
  {
    id: "mum-elec-2",
    name: "Near by Tahir Electrician",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 205,
    phone: "098926 37156",
    status: "To contact",
    notes: "Very highly rated (205 reviews). Excellent local authority, needs simple professional site.",
    source: "Google Maps",
    revenuePotential: 7000
  },
  {
    id: "mum-elec-3",
    name: "Near by Abdul Rahman Electricians",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 36,
    phone: "099306 24529",
    status: "To contact",
    notes: "Active service listing. Easy pitch.",
    source: "Google Maps",
    revenuePotential: 6000
  },
  {
    id: "mum-elec-4",
    name: "Ht Electrician",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 52,
    phone: "081088 94805",
    status: "To contact",
    notes: "Active. Pitch simple contact page + service pricing checklist.",
    source: "Google Maps",
    revenuePotential: 6000
  },
  {
    id: "mum-elec-5",
    name: "AFZAL Electrician",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 12,
    phone: "098207 70579",
    status: "To contact",
    notes: "Smaller active listing. Pitch low-cost 1-page starter website.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-elec-6",
    name: "Royal Electrical Home Repair Service",
    type: "Electrician",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 5,
    phone: "094540 90706",
    status: "To contact",
    notes: "Home repair specialist. Pitch portfolio/service list page.",
    source: "Google Maps",
    revenuePotential: 6000
  },

  // Mumbai - Salons & Spas Andheri West
  {
    id: "mum-salon-1",
    name: "Veda Salon",
    type: "Salon/Spa",
    location: "Versova, Andheri West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 212,
    phone: "",
    status: "To contact",
    notes: "Versova salon. Reach out to get phone or walk in. Pitch online appointment bookings.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "mum-salon-2",
    name: "Blossom Salon",
    type: "Salon/Spa",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 178,
    phone: "",
    status: "To contact",
    notes: "Unisex salon. Reach out to get phone. Needs styling menu and aesthetic design.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "mum-salon-3",
    name: "Diamond Unisex Spa and Salon",
    type: "Salon/Spa",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 120,
    phone: "",
    status: "To contact",
    notes: "Unisex salon. Highly active, needs booking integrations.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "mum-salon-4",
    name: "Palmira Salon N Spa",
    type: "Salon/Spa",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 38,
    phone: "",
    status: "To contact",
    notes: "Boutique salon/spa. High-end clientele appeal, needs premium aesthetic website.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Mumbai - Bandra West Cafes
  {
    id: "mum-cafe-1",
    name: "Morii Cafe",
    type: "Café",
    location: "Bandra West",
    region: "Mumbai",
    rating: 4.5,
    reviewsCount: 184,
    phone: "",
    status: "To contact",
    notes: "Bandra cafe. Relies on Zomato/Swiggy. Pitch: direct orders and branding to bypass OTA commissions.",
    source: "Google Maps",
    revenuePotential: 18000
  },
  {
    id: "mum-cafe-2",
    name: "House of Croissants",
    type: "Café",
    location: "Bandra West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 285,
    phone: "",
    status: "To contact",
    notes: "Bandra. High reviews, premium bakery brand. Pitch interactive menu and pre-order capabilities.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "mum-cafe-3",
    name: "bru baabaa café",
    type: "Café",
    location: "Bandra West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 201,
    phone: "",
    status: "To contact",
    notes: "Bandra. Popular hangout. Pitch brand site with visual gallery and WhatsApp ordering.",
    source: "Google Maps",
    revenuePotential: 18000
  },
  {
    id: "mum-cafe-4",
    name: "Steps Café",
    type: "Café",
    location: "Bandra West",
    region: "Mumbai",
    rating: 4.3,
    reviewsCount: 815,
    phone: "",
    status: "To contact",
    notes: "Bandra. Extremely high review count, very popular. Highly active, high priority target.",
    source: "Google Maps",
    revenuePotential: 20000
  },

  // Mumbai - Gyms Malad West
  {
    id: "mum-gym-1",
    name: "Elite Fitness (by Jerai)",
    type: "Gym",
    location: "Malad West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 97,
    phone: "081042 65514",
    status: "To contact",
    notes: "Jerai equipped gym. Verified no website. Clean lead, call or WhatsApp immediately.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-gym-2",
    name: "E Gym Ijmima",
    type: "Gym",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.6,
    reviewsCount: 884,
    phone: "076859 99444",
    status: "To contact",
    notes: "Ijmima business area. Small chain (has other branches). Pitch a multi-location site or corporate brand identity.",
    source: "Google Maps",
    revenuePotential: 25000
  },
  {
    id: "mum-gym-3",
    name: "Jupito Fitness",
    type: "Gym",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 272,
    phone: "085915 89967",
    status: "To contact",
    notes: "Instagram only. Phone number on Maps might have issues; verify on call. Pitch membership details page.",
    source: "Google Maps",
    instagram: "jupitofitness",
    revenuePotential: 15000
  },
  {
    id: "mum-gym-4",
    name: "ABD Fitness Hub",
    type: "Gym",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 94,
    phone: "",
    status: "To contact",
    notes: "No number on Maps. Reach via Instagram: @111sahil_lifts or walk-in. High reviews, very active.",
    source: "Google Maps",
    instagram: "111sahil_lifts",
    revenuePotential: 15000
  },
  {
    id: "mum-gym-5",
    name: "The Flex Gym",
    type: "Gym",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.4,
    reviewsCount: 155,
    phone: "",
    status: "To contact",
    notes: "Instagram only. Note: recent reviews cite poor upkeep, but active. Pitch simple page to revive online presence.",
    source: "Google Maps",
    revenuePotential: 10000
  },

  // Mumbai - Tailors Andheri West
  {
    id: "mum-tailor-1",
    name: "Raza Fashion Tailor",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 81,
    phone: "",
    status: "To contact",
    notes: "Ladies tailor. Smaller ticket, but easy conversion. Pitch clean design portfolio.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-tailor-2",
    name: "Varsha Tailor (AR Fashion)",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 194,
    phone: "",
    status: "To contact",
    notes: "Highly rated ladies tailor. High probability of conversion.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-tailor-3",
    name: "Pramukh Ladies Tailors",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 22,
    phone: "",
    status: "To contact",
    notes: "Perfect rating (5.0). Needs digital catalog to showcase stitching work.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-tailor-4",
    name: "J M Fashion Tailors",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.6,
    reviewsCount: 76,
    phone: "",
    status: "To contact",
    notes: "Active boutique tailors.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-tailor-5",
    name: "M S Tailors",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 273,
    phone: "",
    status: "To contact",
    notes: "Very high review volume (273). Extremely active, great target.",
    source: "Google Maps",
    revenuePotential: 6000
  },
  {
    id: "mum-tailor-6",
    name: "Venus Ladies Tailor",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 22,
    phone: "",
    status: "To contact",
    notes: "Perfect 5.0 score. Showcases high-quality custom wear.",
    source: "Google Maps",
    revenuePotential: 5000
  },
  {
    id: "mum-tailor-7",
    name: "Iqra Fashion Tailor",
    type: "Tailor/Boutique",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 83,
    phone: "",
    status: "To contact",
    notes: "Active boutique ladies tailor.",
    source: "Google Maps",
    revenuePotential: 5000
  },

  // Mumbai - Dentists Ghatkopar
  {
    id: "mum-dentist-1",
    name: "Dr. Bhavna D. Dedhia",
    type: "Dentist",
    location: "Ghatkopar",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 209,
    phone: "098198 15166",
    status: "To contact",
    notes: "Ghatkopar dentist. Active profile. Note: Dentist market is saturated, but this lead lacks a site.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-dentist-2",
    name: "Dentales – Optimum Dental Care",
    type: "Dentist",
    location: "Ghatkopar",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 182,
    phone: "077770 29097",
    status: "To contact",
    notes: "Optimum Dental Care. Saturated segment, lower priority but has good reviews and contact.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Mumbai - Real Estate Brokers Andheri West & Malad West
  {
    id: "mum-re-1",
    name: "Comfort Real Estate",
    type: "Real Estate",
    location: "Andheri West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 50,
    phone: "098204 82222",
    status: "To contact",
    notes: "Listing unclaimed — owner not managing online presence at all. Pitch: claim listing + simple properties showcase page.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-2",
    name: "Al-Barkat Estate Agents",
    type: "Real Estate",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 101,
    phone: "083691 32945",
    status: "To contact",
    notes: "Owner replies to reviews — engaged. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-3",
    name: "Gurmmeet Real Estate",
    type: "Real Estate",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 59,
    phone: "099206 80071",
    status: "To contact",
    notes: "Owner replies to reviews — engaged. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-4",
    name: "FS Real Estate",
    type: "Real Estate",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 44,
    phone: "091529 47571",
    status: "To contact",
    notes: "Owner replies to reviews — engaged. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-5",
    name: "Shree Krishna Estate Agent",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 35,
    phone: "099308 80093",
    status: "To contact",
    notes: "Buy/sell/rent focus. Pitch showcasing properties with images + WhatsApp lead form.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-6",
    name: "Bharat Estate",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 33,
    phone: "098338 72301",
    status: "To contact",
    notes: "Long-established (25+ yrs). Pitch modernizing their image for new-age buyers.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "mum-re-7",
    name: "Dream Homes Realty",
    type: "Real Estate",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 52,
    phone: "097737 59237",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-8",
    name: "HEM Property Consultant",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 5.0,
    reviewsCount: 42,
    phone: "098924 73825",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-9",
    name: "Lucky Real Estate (Jankalyan Nagar)",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 202,
    phone: "093221 10555",
    status: "To contact",
    notes: "Unconfirmed website status. Highly active with 202 reviews. Confirm website status first.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "mum-re-10",
    name: "Siddhivinayak Real Estate",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.6,
    reviewsCount: 67,
    phone: "099302 71974",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-11",
    name: "Raj Realty Solutions",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.7,
    reviewsCount: 33,
    phone: "098679 68603",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-12",
    name: "Raj Estate Consultants",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.9,
    reviewsCount: 22,
    phone: "098193 20425",
    status: "To contact",
    notes: "Active since 1991. Unconfirmed website status. Confirm website status first.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-re-13",
    name: "Mamta Estate & Property Consultants",
    type: "Real Estate",
    location: "Malad West",
    region: "Mumbai",
    rating: 4.5,
    reviewsCount: 42,
    phone: "098201 37549",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Delhi - Real Estate Brokers
  {
    id: "del-re-1",
    name: "Sahyogi Properties",
    type: "Real Estate",
    location: "Dwarka",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 52,
    phone: "098188 00727",
    status: "To contact",
    notes: "Owner (Mr. Shashank) replies to reviews; alt no. 9958494666. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-2",
    name: "jha real estate",
    type: "Real Estate",
    location: "Dwarka",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 74,
    phone: "097171 58880",
    status: "To contact",
    notes: "Owner (Ashish Jha) replies to reviews. Engaged, warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-3",
    name: "Gupta Property And Associate",
    type: "Real Estate",
    location: "Dwarka",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 72,
    phone: "088028 01704",
    status: "To contact",
    notes: "Women-owned; owner responsive. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-4",
    name: "Godara Realtors Pvt Ltd",
    type: "Real Estate",
    location: "Dwarka",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 44,
    phone: "095400 40048",
    status: "To contact",
    notes: "25+ yrs in Dwarka. Established business.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "del-re-5",
    name: "City Properties & To-Let Services",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 150,
    phone: "085870 15006",
    status: "To contact",
    notes: "Sector 21. High review volume (150) with perfect rating. Excellent candidate.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-6",
    name: "Khatu Shyam Properties",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 62,
    phone: "074001 50555",
    status: "To contact",
    notes: "Sector 9, DC Chowk; owner responsive. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-7",
    name: "Prayas Properties",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 51,
    phone: "099288 63300",
    status: "To contact",
    notes: "Sector 28; owner responsive. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-8",
    name: "Vivaan Real Estate",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 133,
    phone: "088605 72911",
    status: "To contact",
    notes: "Owner replies to reviews. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-9",
    name: "Jai Bholenath Properties",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 52,
    phone: "088029 48119",
    status: "To contact",
    notes: "Owner responsive. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-10",
    name: "Guru Ji Properties",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 60,
    phone: "080765 51166",
    status: "To contact",
    notes: "By Uttam Nagar East metro. Active.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-11",
    name: "Apna Ghar Real Estate & Builder",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 34,
    phone: "087696 96009",
    status: "To contact",
    notes: "Vet first — one review alleges a payment dispute.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-12",
    name: "Sangam Properties",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 116,
    phone: "098719 62606",
    status: "To contact",
    notes: "Opp. Lajpat Nagar metro (Mr. Anil Sikka). Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-13",
    name: "Gaurav Associates",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.7,
    reviewsCount: 172,
    phone: "098112 16599",
    status: "To contact",
    notes: "Dayanand Colony; owner responsive. Warm prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-14",
    name: "Jai Mahavir Property",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 209,
    phone: "092123 98214",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "del-re-15",
    name: "jai mahaveer properties",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 65,
    phone: "092104 87731",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-16",
    name: "BHARDWAJ Real Estate",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 42,
    phone: "089297 10580",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-17",
    name: "Bhardwaj Properties (Sector 3)",
    type: "Real Estate",
    location: "Rohini",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 20,
    phone: "083680 81537",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-18",
    name: "Malhotra Property Dealer",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 22,
    phone: "098184 24345",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-19",
    name: "Poonam Properties",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 4.6,
    reviewsCount: 34,
    phone: "098915 01996",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-20",
    name: "Chhabra Property",
    type: "Real Estate",
    location: "Uttam Nagar",
    region: "Delhi",
    rating: 4.3,
    reviewsCount: 37,
    phone: "092685 99797",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-21",
    name: "Bhalla Properties",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.3,
    reviewsCount: 292,
    phone: "099996 01885",
    status: "To contact",
    notes: "Unconfirmed website status. High review count (292). Confirm website status first.",
    source: "Google Maps",
    revenuePotential: 20000
  },
  {
    id: "del-re-22",
    name: "Chopra Properties",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 24,
    phone: "098105 06264",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-23",
    name: "Wadhwa Properties",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.0,
    reviewsCount: 72,
    phone: "098114 67899",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-re-24",
    name: "Alliance Real Estate",
    type: "Real Estate",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 11,
    phone: "098715 09000",
    status: "To contact",
    notes: "Unconfirmed website status. Confirm website status by Googling name before pitching.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Delhi - Gyms
  {
    id: "del-gym-1",
    name: "My Fitness Destination",
    type: "Gym",
    location: "Rohini (North Ex Mall)",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 1173,
    phone: "093107 08676",
    status: "To contact",
    notes: "Owner replies to reviews. Engaged, high-review volume, top prospect.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-2",
    name: "Swag Fit Gym and Studio",
    type: "Gym",
    location: "Rohini Sector 16",
    region: "Delhi",
    rating: 5.0,
    reviewsCount: 368,
    phone: "098184 87484",
    status: "To contact",
    notes: "Perfect 5.0 score with 368 reviews. Active.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-3",
    name: "Red Zone Fitness",
    type: "Gym",
    location: "Rohini Sector 3",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 351,
    phone: "084483 35775",
    status: "To contact",
    notes: "Active fitness center in Rohini.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-4",
    name: "Studio 4 Gym",
    type: "Gym",
    location: "Dwarka Sector 4",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 219,
    phone: "098212 12266",
    status: "To contact",
    notes: "Instagram only — no own site. Pitch: brand site + membership options.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-5",
    name: "Physio Flex Gym",
    type: "Gym",
    location: "Pitampura / Saraswati Vihar",
    region: "Delhi",
    rating: 4.7,
    reviewsCount: 129,
    phone: "098104 75557",
    status: "To contact",
    notes: "Active gym with steady reviews.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-6",
    name: "Mechanixx Fitness",
    type: "Gym",
    location: "Rohini Sector 15",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 122,
    phone: "088021 90935",
    status: "To contact",
    notes: "Active Rohini gym.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-7",
    name: "BURNOUT Fitness Club",
    type: "Gym",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 451,
    phone: "094856 00073",
    status: "To contact",
    notes: "Verified no website. Active Lajpat Nagar gym with 451 reviews. High priority.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-8",
    name: "Real Steel Gym",
    type: "Gym",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.6,
    reviewsCount: 211,
    phone: "099999 01167",
    status: "To contact",
    notes: "Verified no website. Good candidate.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-9",
    name: "Fitness Step",
    type: "Gym",
    location: "Lajpat Nagar",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 140,
    phone: "011 3560 8235",
    status: "To contact",
    notes: "Verified no website. Landline number listed.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-10",
    name: "Fitness 24/7",
    type: "Gym",
    location: "Janakpuri",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 283,
    phone: "097112 88275",
    status: "To contact",
    notes: "Verified no website. Active Janakpuri gym.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-11",
    name: "Star Fitness Janakpuri",
    type: "Gym",
    location: "Janakpuri",
    region: "Delhi",
    rating: 4.7,
    reviewsCount: 164,
    phone: "082855 42990",
    status: "To contact",
    notes: "Verified no website. Active.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-12",
    name: "Muscular Aptitude Gym",
    type: "Gym",
    location: "Laxmi Nagar",
    region: "Delhi",
    rating: 4.9,
    reviewsCount: 974,
    phone: "082877 48167",
    status: "To contact",
    notes: "Verified no website. Almost 1,000 reviews with a 4.9 rating. Prime target.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "del-gym-13",
    name: "The Wonder Fitness Gym",
    type: "Gym",
    location: "Laxmi Nagar",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 56,
    phone: "088821 36195",
    status: "To contact",
    notes: "Verified no website. Active.",
    source: "Google Maps",
    revenuePotential: 15000
  },

  // Himachal Pradesh - Cafés & Restaurants
  {
    id: "hp-cafe-1",
    name: "Southern Souls Cafe",
    type: "Café",
    location: "Mall Road, Manali",
    region: "Himachal Pradesh",
    rating: 4.9,
    reviewsCount: 2126,
    phone: "098852 10212",
    status: "To contact",
    notes: "Women-owned; owner replies to reviews — warm lead. South Indian (pure veg). Great reviews.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "hp-cafe-2",
    name: "Magnolia Bengali Restaurant",
    type: "Café",
    location: "Mall Road, Manali",
    region: "Himachal Pradesh",
    rating: 4.8,
    reviewsCount: 245,
    phone: "089725 08075",
    status: "To contact",
    notes: "Bengali restaurant on Mall Road.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "hp-cafe-3",
    name: "Madras Cafe",
    type: "Café",
    location: "Log Huts Rd, Manali",
    region: "Himachal Pradesh",
    rating: 4.6,
    reviewsCount: 1890,
    phone: "070187 27083",
    status: "To contact",
    notes: "South Indian café, near Mall Road.",
    source: "Google Maps",
    revenuePotential: 12000
  },

  // Uttarakhand - Cafés & Restaurants
  {
    id: "ut-cafe-1",
    name: "Mastana Musafir Cafe",
    type: "Café",
    location: "Laxman Jhula, Rishikesh",
    region: "Uttarakhand",
    rating: 4.7,
    reviewsCount: 492,
    phone: "070036 55526",
    status: "To contact",
    notes: "Women-owned; Ganga-view, Laxman Jhula. Multi-cuisine / Korean. High priority warm lead.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "ut-cafe-2",
    name: "The Monkey House Cafe",
    type: "Café",
    location: "Tapovan, Rishikesh",
    region: "Uttarakhand",
    rating: 4.3,
    reviewsCount: 550,
    phone: "074569 17677",
    status: "To contact",
    notes: "Multi-cuisine rooftop café.",
    source: "Google Maps",
    revenuePotential: 12000
  },

  // Mumbai - Cafés & Restaurants
  {
    id: "mum-cafe-5",
    name: "Bonfire – All Day Dining",
    type: "Café",
    location: "Versova, Andheri West",
    region: "Mumbai",
    rating: 4.8,
    reviewsCount: 463,
    phone: "070390 31233",
    status: "To contact",
    notes: "Global cuisine restaurant in Versova. Verified no website. High rating.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "mum-cafe-6",
    name: "Quesso Veg Ristorante",
    type: "Café",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.3,
    reviewsCount: 3053,
    phone: "022 2634 9966",
    status: "To contact",
    notes: "Italian/veg restaurant. Massively popular with over 3,000 reviews! Needs a simple elegant site.",
    source: "Google Maps",
    revenuePotential: 15000
  },
  {
    id: "mum-cafe-7",
    name: "Victory Restaurant",
    type: "Café",
    location: "Andheri West",
    region: "Mumbai",
    rating: 4.2,
    reviewsCount: 1726,
    phone: "089764 12429",
    status: "To contact",
    notes: "Mughlai / Kerala restaurant. Sizable review count (1726) but no own domain.",
    source: "Google Maps",
    revenuePotential: 12000
  },

  // Delhi - Cafés & Restaurants
  {
    id: "del-cafe-1",
    name: "Kartoon Cafe",
    type: "Café",
    location: "Rajouri Garden",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 467,
    phone: "098736 61133",
    status: "To contact",
    notes: "Cafe / multi-cuisine in Rajouri Garden. Highly rated (4.8).",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "del-cafe-2",
    name: "TYM (The Young Malang)",
    type: "Café",
    location: "Rajouri Garden",
    region: "Delhi",
    rating: 4.8,
    reviewsCount: 174,
    phone: "070515 15858",
    status: "To contact",
    notes: "Chinese cuisine restaurant in Rajouri Garden. Pitch direct ordering.",
    source: "Google Maps",
    revenuePotential: 12000
  },
  {
    id: "del-cafe-3",
    name: "Elia Kitchen & Bar",
    type: "Café",
    location: "Rajouri Garden",
    region: "Delhi",
    rating: 4.4,
    reviewsCount: 1577,
    phone: "090838 33434",
    status: "To contact",
    notes: "North Indian / rooftop. Huge reviews (1577) but lacks domain.",
    source: "Google Maps",
    revenuePotential: 15000
  }
];

const OUTREACH_TEMPLATES = {
  whatsapp: `Namaste {name} ji, I came across {name} on {source} — you've got great reviews ({rating}★, {reviewsCount} reviews) but I noticed you don't have your own website yet. I build simple, mobile-friendly websites for local {location} businesses that help customers find you on Google and message you directly. I can make a free 1-page demo for {name} — no obligation. Shall I send it over?

Regards,
Sanjeev Yadav
Business Analyst (Ex-Deloitte | Ex-Accenture | Ex-Nielsen)
LinkedIn: https://www.linkedin.com/in/sanjeev-yadav-46592a258/`,
  
  call: `Hi, am I speaking with the owner of {name}? I help {location} businesses like yours get found on Google. I noticed you don't have a website — most customers check online before visiting. I can show you a quick demo I've made specifically for {name}. Do you have two minutes, or should I WhatsApp it?`,
  
  email: `Subject: A website for {name} — free demo inside

Hi,

I found {name} on {source} — strong reviews ({rating}★), but no website of your own. That means customers who Google you land on a directory instead of you, and can't see your services, photos, or contact you directly.

I build clean, mobile-first websites for local {location} businesses that show up on Google and turn searches into calls. I'd like to build you a free one-page demo — you only pay if you love it.

Reply "yes" and I'll have it ready in 48 hours.

Regards,
Sanjeev Yadav
Business Analyst (Ex-Deloitte | Ex-Accenture | Ex-Nielsen)
LinkedIn: https://www.linkedin.com/in/sanjeev-yadav-46592a258/`,
  
  demoFirst: `Made this website demo for {name} in 20 mins — here is the link. Want me to make it live for your business?

Regards,
Sanjeev Yadav
Business Analyst (Ex-Deloitte | Ex-Accenture | Ex-Nielsen)
LinkedIn: https://www.linkedin.com/in/sanjeev-yadav-46592a258/`
};

const PRICING_ANCHORS = {
  "Café": { min: 5000, max: 20000, recommended: 12000 },
  "Gym": { min: 10000, max: 25000, recommended: 15000 },
  "Electrician": { min: 5000, max: 10000, recommended: 6000 },
  "Salon/Spa": { min: 8000, max: 20000, recommended: 12000 },
  "Tailor/Boutique": { min: 5000, max: 10000, recommended: 5000 },
  "Dentist": { min: 12000, max: 25000, recommended: 15000 },
  "Adventure/Tour": { min: 8000, max: 15000, recommended: 10000 },
  "Real Estate": { min: 10000, max: 30000, recommended: 15000 },
  "Other": { min: 5000, max: 15000, recommended: 8000 }
};
